### ISSUE TITLE
NameError: name 'filepath' is not defined

### ISSUE THREAD

**Issue by xsaren11** [Xaque8787/m3uparser#1]
Hi,

I have an issue with parsing my file

Processing line: #EXTINF:-1 tvg-id="#.No.Channel.#" tvg-name="✺ FR ⋆ GENERALE FHD ✺" tvg-logo="http://lg.mygolden.xyz:8080/logo/EUROPE/FRANCE/flag_france.png" group-title="FR ❖ GENERALE",✺ FR ⋆ GENERALE FHD ✺
Processing line: http://maxprime.xyz:80/Y27P36K66B57Z3/B2MR6VBCL5L7HQNJ/2586
Traceback (most recent call last):
  File "/usr/src/app/parser.py", line 115, in <module>
    with open(filepath, "w") as f:
NameError: name 'filepath' is not defined

Could you suggest what could be the issue?

BR
Cris

**Comment by Xaque8787** [comment]
> Hi,
> 
> I have an issue with parsing my file
> 
> Processing line: #EXTINF:-1 tvg-id="#.No.Channel.#" tvg-name="✺ FR ⋆ GENERALE FHD ✺" tvg-logo="http://lg.mygolden.xyz:8080/logo/EUROPE/FRANCE/flag_france.png" group-title="FR ❖ GENERALE",✺ FR ⋆ GENERALE FHD ✺
> Processing line: http://maxprime.xyz:80/Y27P36K66B57Z3/B2MR6VBCL5L7HQNJ/2586
> Traceback (most recent call last):
>   File "/usr/src/app/parser.py", line 115, in <module>
>     with open(filepath, "w") as f:
> NameError: name 'filepath' is not defined
> 
> Could you suggest what could be the issue?
> 
> BR
> Cris

Currently this only works with iptorrents m3u. Does not support other providers VOD. If you supplied a sample of your providers VOD .m3u with redacted account info I could look into adding support for that.

**Comment by xsaren11** [comment]
Here it is example of iptv.m3u file from china provider 
[tv_channels_Y27P36K66B57Z3_plus (1).zip](https://github.com/Xaque8787/m3uparser/files/14115321/tv_channels_Y27P36K66B57Z3_plus.1.zip)

**Comment by Xaque8787** [comment]
New update should allow you to process VOD now, however, the m3u you provided me was one, a bit nefarious because it was npt a .m3u file extension, rather it was a shell script. And when I safely looked at its contents it was very large with poorly named titles. If you read the instructions in the readme now, hopefully you will be able to add some SCRUB_HEADER and REMOVE_TERMS values to get something to work. In the group-title= value of your m3u you need to have TV shows with Season Episode values in some standard format like SXXEXX or 00x00, and Movies require a year release like The Movie (2012) or some variation like that. Good luck and let me know if you get it working. Marking this issue closed.
